apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: bulletinboard
  labels:
    app: notification
    component: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
        component: business
    spec:
      containers:
      - name: notification
        image: pavel2007/notification:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: notification-config
        - secretRef:
            name: common-secret
        - secretRef:
            name: notification-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"