apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: bulletinboard
  labels:
    app: apigateway
    component: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
        component: gateway
    spec:
      containers:
      - name: apigateway
        image: pavel2007/apigateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: apigateway-config
        - secretRef:
            name: common-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"