apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        component: auth
    spec:
      containers:
      - name: keycloak
        image: pavel2007/keycloak-custom:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 9000
        env:
        # База данных (из common-secret)
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: POSTGRES_PASSWORD
        # Остальные переменные из keycloak-config
        - name: KC_DB
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB
        - name: KC_DB_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB_URL
        - name: KC_DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_DB_USERNAME
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_BOOTSTRAP_ADMIN_USERNAME
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KC_BOOTSTRAP_ADMIN_PASSWORD
        - name: KC_IMPORT
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_IMPORT
        - name: KC_SMTP_FROM
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_FROM
        - name: KC_SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_HOST
        - name: KC_SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_PORT
        - name: KC_SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_USER
        - name: KC_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KC_SMTP_PASSWORD
        - name: KC_SMTP_STARTTLS
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_STARTTLS
        - name: KC_SMTP_AUTH
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_SMTP_AUTH
        - name: KC_HOSTNAME_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_URL
        - name: KC_HOSTNAME_ADMIN_URL
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_ADMIN_URL
        - name: KC_HOSTNAME_STRICT
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HOSTNAME_STRICT
        - name: KC_PROXY
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_PROXY
        - name: PROXY_ADDRESS_FORWARDING
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: PROXY_ADDRESS_FORWARDING
        - name: KC_HTTP_ENABLED
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HTTP_ENABLED
        - name: KC_HEALTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: keycloak-config
              key: KC_HEALTH_ENABLED
        command:
        - /opt/keycloak/bin/kc.sh
        - start-dev
        - --import-realm
        - --spi-events-listener-my-event-listener-enabled=true
        - --spi-events-listener-my-event-listener-rabbitmqhost=rabbitmq-service
        - --spi-events-listener-my-event-listener-rabbitmqport=5672
        - --spi-events-listener-my-event-listener-rabbitmqusername=rmuser
        - --spi-events-listener-my-event-listener-rabbitmqpassword=rmpassword
        - --spi-events-listener-my-event-listener-rabbitmqvirtualhost=/
        volumeMounts:
        - name: keycloak-import
          mountPath: /opt/keycloak/data/import
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
      volumes:
      - name: keycloak-import
        configMap:
          name: keycloak-import