apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bulletinboard

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: keycloak-config
  envs:
  - config.env
- name: keycloak-import
  files:
  - realm-export.json

secretGenerator:
- name: keycloak-secret
  envs:
  - secret.env