apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin
  namespace: bulletinboard
  labels:
    app: bulletin
    component: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
        component: business
    spec:
      containers:
      - name: bulletin
        image: pavel2007/bulletin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: bulletin-config
        - secretRef:
            name: common-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"