apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: pavel2007/auth:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: auth-config
        - secretRef:
            name: common-secret
        - secretRef:
            name: auth-secret
