apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: bulletinboard
  labels:
    app: chat
    component: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
        component: business
    spec:
      containers:
      - name: chat
        image: pavel2007/chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: chat-config
        - secretRef:
            name: common-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"