apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: common-config
  envs:
  - common-config.env

secretGenerator:
- name: common-secret
  envs:
  - common-secret.env
  options:
    disableNameSuffixHash: false