apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bulletinboard

resources:
  - namespace.yaml
  - infrastructure/postgres
  - infrastructure/rabbitmq
  - infrastructure/keycloak
  - infrastructure/minio
  - infrastructure/eureka
  - services/auth
  - services/bulletin
  - services/notification
  - services/chat
  - services/client
  - infrastructure/apigateway
  - ingress/main-ingress.yaml
  - ingress/keycloak-ingress.yaml
  - ingress/minio-ingress.yaml
  - ingress/minio-console-ingress.yaml


configMapGenerator:
- name: common-config
  envs:
  - common-config.env

secretGenerator:
- name: common-secret
  envs:
  - common-secret.env
