apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: pavel2007/keycloak-custom:latest
        ports:
        - containerPort: 8080
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: keycloak-config
        - secretRef:
            name: common-secret
        - secretRef:
            name: keycloak-secret
        command:
        - start-dev
        - --import-realm
        - --spi-import-provider-single-file-file=/opt/keycloak/data/import/realm-export.json
        - --spi-import-provider-single-file-override=false
        - --spi-events-listener-my-event-listener-enabled=true
        - --spi-events-listener-my-event-listener-rabbitmqhost=rabbitmq-service
        - --spi-events-listener-my-event-listener-rabbitmqport=5672
        - --spi-events-listener-my-event-listener-rabbitmqusername=rmuser
        - --spi-events-listener-my-event-listener-rabbitmqpassword=rmpassword
        - --spi-events-listener-my-event-listener-rabbitmqvirtualhost=/
