apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bulletinboard

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
- name: notification-config
  envs:
  - config.env

secretGenerator:
# Notification использует только общие секреты из common-secret