apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin-deployment
  labels:
    app: bulletin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
    spec:
      containers:
      - name: bulletin
        image: pavel2007/bulletin:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: common-config
        - configMapRef:
            name: bulletin-config
        - secretRef:
            name: common-secret
