apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulletin
  labels:
    app: bulletin
    component: business
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulletin
  template:
    metadata:
      labels:
        app: bulletin
        component: business
    spec:
      containers:
      - name: bulletin
        image: pavel2007/bulletin:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Из common-config
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: RABBITMQ_PORT
        - name: RABBITMQ_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: RABBITMQ_USERNAME
        - name: DOCKER_KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: KEYCLOAK_ISSUER_URI
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: KEYCLOAK_CLIENT_ID
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: POSTGRES_USER
        - name: EUREKA_PATH
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EUREKA_PATH
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
        - name: MANAGEMENT_SECURITY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: MANAGEMENT_SECURITY_ENABLED
        # Из common-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: POSTGRES_PASSWORD
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: RABBITMQ_PASSWORD
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: common-secret
              key: KEYCLOAK_CLIENT_SECRET
        - name: KEYCLOAK_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: KEYCLOAK_ISSUER_URI
        # Из bulletin-config
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: bulletin-config
              key: SERVER_PORT
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: bulletin-config
              key: DB_URL
        - name: EUREKA_INSTANCE_HOSTNAME
          valueFrom:
              configMapKeyRef:
                name: bulletin-config
                key: EUREKA_INSTANCE_HOSTNAME
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          valueFrom:
              configMapKeyRef:
                name: bulletin-config
                key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
        - name: EUREKA_INSTANCE_NON_SECURE_PORT_ENABLED
          valueFrom:
              configMapKeyRef:
                name: bulletin-config
                key: EUREKA_INSTANCE_NON_SECURE_PORT_ENABLED
        - name: EUREKA_INSTANCE_NON_SECURE_PORT
          valueFrom:
              configMapKeyRef:
                name: bulletin-config
                key: EUREKA_INSTANCE_NON_SECURE_PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"