spring:
  application:
    name: bulletin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pozdravliator}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:iamdeadlytired795795}
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rmuser}
    password: ${RABBITMQ_PASSWORD:rmpassword}
    virtual-host: ${RABBITMQ_VHOST:/}
    connection-timeout: 5000
    listener:
      simple:
        default-requeue-rejected: false
  amqp:
    deserialization:
      trust:
        all: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/oAuth}
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/oAuth}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:myclient}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:jeWE38sfUCQJhplYyeJ7IwcMk8P27fVh}
            scope: openid
app:
  keycloak:
    client-id: ${KEYCLOAK_CLIENT_ID:myclient}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:jeWE38sfUCQJhplYyeJ7IwcMk8P27fVh}
    out-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/oAuth}
    docker-uri: ${DOCKER_KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/oAuth}

logging:
  level:
    com.example.chat.infrastructure.filter: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %thread | %logger{36} | %msg%n"

server:
  port: ${SERVER_PORT:8080}

